name = "EarthData"
uuid = "0ce7a1f8-0645-46c2-a0bb-6c09c29d93e9"
authors = ["Maarten Pronk <git@evetion.nl> and contributors"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[weakdeps]
AWSS3 = "1c724243-ef5b-51ab-93f4-b0a88ac62a95"

[extensions]
EarthDataAWSExt = "AWSS3"

[compat]
AWSS3 = "0.11"
Extents = "0.1"
HTTP = "1.9"
JSON3 = "1.13"
StructTypes = "1.10"
TimeZones = "1.11"
julia = "1.6"

[extras]
AWSS3 = "1c724243-ef5b-51ab-93f4-b0a88ac62a95"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Test", "AWSS3", "Documenter"]
